table dproduto
	lineageTag: 12b58f20-bf17-4d15-a690-4d116890e4ea

	column produto_id
		dataType: double
		lineageTag: ef3f1fd3-2c9d-4979-9ebb-b519fb76d57d
		summarizeBy: none
		sourceColumn: produto_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nome_produto
		dataType: string
		lineageTag: c5667fd9-054c-4941-ad26-a8839e0d787c
		summarizeBy: none
		sourceColumn: nome_produto

		annotation SummarizationSetBy = Automatic

	column codigo_atc
		dataType: string
		lineageTag: f3812eea-4c56-4f0f-97e6-3bb87d756ae3
		summarizeBy: none
		sourceColumn: codigo_atc

		annotation SummarizationSetBy = Automatic

	column categoria
		dataType: string
		lineageTag: 6de43e67-5a36-4c40-8ffd-479a15849a07
		summarizeBy: none
		sourceColumn: categoria

		annotation SummarizationSetBy = Automatic

	column grupo_terapeutico
		dataType: string
		lineageTag: 48f3fbf3-0875-40cc-89a7-9ebbd68d8be5
		summarizeBy: none
		sourceColumn: grupo_terapeutico

		annotation SummarizationSetBy = Automatic

	column preco_unitario
		dataType: double
		lineageTag: ceef0726-5c83-42b6-a88f-220f86158fde
		summarizeBy: none
		sourceColumn: preco_unitario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column custo_unitario
		dataType: double
		lineageTag: 80efef2c-4b84-4eed-aec4-99dedfd8ca3b
		summarizeBy: none
		sourceColumn: custo_unitario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column margem_percentual
		dataType: double
		lineageTag: 7629c493-8221-40bd-a784-63f10487bc16
		summarizeBy: none
		sourceColumn: margem_percentual

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column exige_receita
		dataType: double
		lineageTag: 42bfd088-ca45-4bf8-8c72-2a87228f64af
		summarizeBy: none
		sourceColumn: exige_receita

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Med. controlados'
		dataType: string
		lineageTag: 7c9413c0-a56d-473a-8602-b5c7ce0dec33
		summarizeBy: none
		sourceColumn: Med. controlados

		annotation SummarizationSetBy = Automatic

	partition dproduto = m
		mode: import
		source =
				let
				    Fonte = Odbc.DataSource("driver={SQLite3 ODBC Driver};database=C:\Users\Claudio\Desktop\3º Projeto MBA - Datachallenger\documentação projeto\Base\farma_xperiun.db;dsn=SQLite3 Datasource", [HierarchicalNavigation=true]),
				    d_produto_Table = Fonte{[Name="d_produto",Kind="Table"]}[Data],
				    #"Outras Colunas Removidas" = Table.SelectColumns(d_produto_Table,{"produto_id", "nome_produto", "codigo_atc", "categoria", "grupo_terapeutico", "preco_unitario", "custo_unitario", "margem_percentual", "exige_receita"}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Outras Colunas Removidas", "Personalizar", each if [exige_receita] = 0 then "Não" else if [exige_receita] = 1 then "Sim" else null),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Coluna Condicional Adicionada",{{"Personalizar", "Med. controlados"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Med. controlados", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

