table fvendas
	lineageTag: dd601e0d-1137-4df3-85bd-1f2625a6dc77

	column data
		dataType: dateTime
		formatString: Short Date
		lineageTag: 967c628e-3f01-44fb-8dd2-a55902ca09a0
		summarizeBy: none
		sourceColumn: data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hora
		dataType: double
		lineageTag: 3f3a416e-fa2d-469b-9e38-70f22aea760b
		summarizeBy: sum
		sourceColumn: hora

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column turno_id
		dataType: double
		lineageTag: de0c1cd2-01d2-48e2-8d11-68bbc5655158
		summarizeBy: none
		sourceColumn: turno_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column produto_id
		dataType: double
		lineageTag: d2a0ec7a-de78-4140-b41d-23f13b2c20b9
		summarizeBy: none
		sourceColumn: produto_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fornecedor_id
		dataType: double
		lineageTag: b1d9b333-8cb5-42b7-92c4-1671be937d5d
		summarizeBy: none
		sourceColumn: fornecedor_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column quantidade
		dataType: double
		lineageTag: 4fc7f0ca-9d61-46b8-b05c-86ad4546017b
		summarizeBy: sum
		sourceColumn: quantidade

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column preco_unitario
		dataType: double
		lineageTag: 5c669b49-a2df-4958-a78b-33508bc42678
		summarizeBy: sum
		sourceColumn: preco_unitario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column desconto
		dataType: double
		lineageTag: dbc6fb83-161e-472b-8aed-16c92709b4d2
		summarizeBy: sum
		sourceColumn: desconto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column custo_total
		dataType: double
		lineageTag: 1134c262-1ef4-4bf0-a953-61739fdba9b2
		summarizeBy: sum
		sourceColumn: custo_total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column forma_pagamento
		dataType: string
		lineageTag: eb24b77b-800a-459d-a651-6e7a4e6c6c3d
		summarizeBy: none
		sourceColumn: forma_pagamento

		annotation SummarizationSetBy = Automatic

	column venda_id
		dataType: double
		lineageTag: f76fea71-8105-409e-8785-f4b33a7d4c5b
		summarizeBy: sum
		sourceColumn: venda_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fvendas = m
		mode: import
		queryGroup: Fatos
		source =
				let
				    Fonte = Database{[Name="vw_vendas",Kind="View"]}[Data],
				    Tipar = Table.TransformColumnTypes(Fonte,{{"data", type date}})
				in
				    Tipar

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

